# Data Loading

## Dataset Description

Your challenge in this competition is to identify which species (birds, amphibians, mammals, reptiles, insects) are calling in recordings made in the Brazilian Pantanal. This is an important task for scientists who monitor animal populations for conservation purposes. More accurate solutions could enable more comprehensive monitoring.

This competition uses a hidden test set. When your submitted notebook is scored, the actual test data will be made available to your notebook.

### Files

`train_audio/` The training data consists of short recordings of individual bird, amphibian, reptile, mammal, and insect sounds generously uploaded by users of xeno-canto.org and iNaturalist. These files have been resampled to 32 kHz where applicable to match the test set audio and converted to the ogg format. Filenames consist of [collection][file_id_in_collection].ogg. The training data should have nearly all relevant files; we expect there is no benefit to looking for more on xeno-canto.org or iNaturalist and appreciate your cooperation in limiting the burden on their servers. If you do, please make sure to adhere to the scraping rules of these data portals.

`test_soundscapes/` When you submit a notebook, the test_soundscapes directory will be populated with approximately 600 recordings to be used for scoring. They are 1 minute long and in ogg audio format, resampled to 32 kHz. The file names have the general form of BC2026_Test_<file ID>_<site>_<date>_<time in UTC>.ogg (e.g., file BC2026_Test_0001_S05_20250227_010002.ogg has file ID 0001, was recorded at site S05 on Feb 27 2025 at 01:00 UTC). It should take your submission notebook approximately five minutes to load all the test soundscapes. Not all species from the training data actually occur in the test data.

`train_soundscapes/` Additional audio data from roughly the same recording locations as the test_soundscapes. Filenames follow the same naming convention as the test_soundscapes; although some recording sites overlap between train and test, precise recording dates and times do NOT overlap with recordings of the hidden test data. This year, some of the train_soundscapes have been labeled by expert annotators, and we provide the ground truth for a subset of train_soundscapes in train_soundscapes_labels.csv with columns filename referencing the soundscape file, start and end referencing the 5-second segment for which column primary_label provides a semicolon-separated list of species codes that have been marked as present in this segment.

**Important note:** Some species with occurrences in the hidden test data might only have train samples in the labeled portion of train_soundscapes and not in the train_audio (XC and iNat data). However, not all species from train_soundscapes have occurrences in the test_soundscapes.

`train.csv` A wide range of metadata is provided for the training data. The most directly relevant fields are:

- primary_label: A code for the species (eBird code for birds, iNaturalist taxon ID for non-birds). You can review detailed information about the species by appending codes to eBird and iNaturalist taxon URL, such as https://ebird.org/species/brnowl for the Barn Owl or https://www.inaturalist.org/taxa/41970 for the Jaguar. Not all species have their own pages; some links might fail.

- secondary_labels: List of species labels that have been marked by recordists to also occur in the recording. Can be incomplete.

- latitude & longitude: Coordinates for where the recording was taken. Some bird species may have local call 'dialects,' so you may want to seek geographic diversity in your training data.

- author: The user who provided the recording. Unknown if no name was provided.

- filename: The name of the associated audio file.

- rating: Values in 1..5 (1 - low quality, 5 - high quality; 0.5 reduction in rating when background species are present) provided by users of Xeno-canto; 0 implies no rating is available; iNaturalist does not provide quality ratings.

- collection: Either XC or iNat, indicating which collection the recording was taken from. Filenames also reference the collection and the ID within that collection.

`sample_submission.csv` A valid sample submission.

- row_id: A slug of [soundscape_filename]_[end_time] for the prediction; e.g., Segment 00:15-00:20 of 1-minute test soundscape BC2026_Test_0001_S05_20250227_010002.ogg has row ID BC2026_Test_0001_S05_20250227_010002_20.

- [species_id]: There are 234 species ID columns. You will need to predict the probability of the presence of each species for each row.
taxonomy.csv - Data on the different species, including iNaturalist taxon ID and class name (Aves, Amphibia, Mammalia, Insecta, Reptilia). Most insect species in this competition have not been identified on species level and instead occur as sonotypes (e.g., 47158son16 as insect sonotype 16); these sonotypes are treated as classes despite the lack of species ID and some of them also occur in the test data. The 234 rows of this file represent the 234 class columns in the submission file. primary_label specifies the submission file column name.

`recording_location.txt` - Some high-level information on the recording location (Pantanal, Brazil).

In [1]:
import librosa
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df_train = pd.read_csv("../birdclef-2026/train.csv")
df_train_soundscapes = pd.read_csv("../birdclef-2026/train_soundscapes_labels.csv")
df_taxonomy = pd.read_csv("../birdclef-2026/taxonomy.csv")

In [3]:
df_train

,primary_label,secondary_labels,type,latitude,longitude,scientific_name,common_name,class_name,inat_taxon_id,author,license,rating,url,filename,collection
0,1161364,[],[],-22.7562,-46.8666,Guyalna cuta,Guyalna cuta,Insecta,1161364,Lucas Barbosa,cc-by-nc,0.0,https://static.inaturalist.org/sounds/1216197....,1161364/iNat1216197.ogg,iNat
1,1161364,[],[],-22.7558,-46.8700,Guyalna cuta,Guyalna cuta,Insecta,1161364,Lucas Barbosa,cc-by-nc,0.0,https://static.inaturalist.org/sounds/1114648....,1161364/iNat1114648.ogg,iNat
2,1161364,[],[],-22.7547,-46.8728,Guyalna cuta,Guyalna cuta,Insecta,1161364,Lucas Barbosa,cc-by-nc,0.0,https://static.inaturalist.org/sounds/810195.m...,1161364/iNat810195.ogg,iNat
3,1161364,[],[],-22.7547,-46.8728,Guyalna cuta,Guyalna cuta,Insecta,1161364,Lucas Barbosa,cc-by-nc,0.0,https://static.inaturalist.org/sounds/818781.m...,1161364/iNat818781.ogg,iNat
4,1161364,[],[],-22.7426,-46.8985,Guyalna cuta,Guyalna cuta,Insecta,1161364,Lucas Barbosa,cc-by-nc,0.0,https://static.inaturalist.org/sounds/556514.m...,1161364/iNat556514.ogg,iNat
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35544,yeofly1,[],['call'],-6.7281,-76.4181,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves,16567,GABRIEL LEITE,by-nc-sa,4.0,https://xeno-canto.org/762473/download,yeofly1/XC762473.ogg,XC
35545,yeofly1,[],"['call', ' song']",-16.0538,-49.6040,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves,16567,JAYRSON ARAUJO DE OLIVEIRA,by-nc-sa,5.0,https://xeno-canto.org/818328/download,yeofly1/XC818328.ogg,XC
35546,yeofly1,[],['song'],5.9002,-74.8485,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves,16567,Jerome Fischer,by-nc-sa,4.0,https://xeno-canto.org/425545/download,yeofly1/XC425545.ogg,XC
35547,yeofly1,[],['song'],3.3821,-61.4464,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves,16567,GABRIEL LEITE,by-nc-sa,4.0,https://xeno-canto.org/456230/download,yeofly1/XC456230.ogg,XC
35548,yeofly1,[],['song'],-19.4144,-42.4151,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves,16567,Roney Souza,by-nc-sa,5.0,https://xeno-canto.org/298884/download,yeofly1/XC298884.ogg,XC

In [4]:
df_train_soundscapes

,filename,start,end,primary_label
0,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:00,00:00:05,22961;23158;24321;517063;65380
1,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:05,00:00:10,22961;23158;24321;517063;65380
2,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:10,00:00:15,22961;23158;24321;517063;65380
3,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:15,00:00:20,22961;23158;24321;517063;65380
4,BC2026_Train_0039_S22_20211231_201500.ogg,00:00:20,00:00:25,22961;23158;24321;517063;65380
...,...,...,...,...
1473,BC2026_Train_0055_S22_20220219_200000.ogg,00:00:35,00:00:40,555146;65380
1474,BC2026_Train_0055_S22_20220219_200000.ogg,00:00:40,00:00:45,517063;555146
1475,BC2026_Train_0055_S22_20220219_200000.ogg,00:00:45,00:00:50,517063;555146
1476,BC2026_Train_0055_S22_20220219_200000.ogg,00:00:50,00:00:55,517063;555146;66971
1477,BC2026_Train_0055_S22_20220219_200000.ogg,00:00:55,00:01:00,517063;555146;66971

In [5]:
df_taxonomy

,primary_label,inat_taxon_id,scientific_name,common_name,class_name
0,1161364,1161364,Guyalna cuta,Guyalna cuta,Insecta
1,116570,116570,Caiman yacare,Southern Spectacled Caiman,Reptilia
2,1176823,1176823,Leptodactylus luctator,Wrestler Frog,Amphibia
3,1491113,1491113,Adenomera guarani,Guaraní leaf-litter frog,Amphibia
4,1595929,1595929,Lysapsus limellum,Uruguay Harlequin Frog,Amphibia
...,...,...,...,...,...
229,yebela1,16714,Elaenia flavogaster,Yellow-bellied Elaenia,Aves
230,yecmac,73272,Primolius auricollis,Golden-collared Macaw,Aves
231,yecpar,19215,Brotogeris chiriri,Yellow-chevroned Parakeet,Aves
232,yehcar1,1432779,Daptrius chimachima,Yellow-headed Caracara,Aves
233,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves

For now I am going to ignore the secondary labels as they concern only a small fraction of the data.

In [6]:
print(
    f"Percentage of train audio with secondary labels: {(df_train['secondary_labels'] != '[]').sum() / len(df_train) * 100:.2f}%"
)

Percentage of train audio with secondary labels: 12.30%

There are very many different types of calls, songs, etc... It would likely make sense combine them into different categories e.g. songs, calls, etc so that there can be clearer similarities between the calories. I've listed them here.

In [7]:
import ast

list_types = df_train["type"].unique().tolist()
list_types = [ast.literal_eval(lst) for lst in list_types]
possible_types = set(x for sublist in list_types for x in sublist)
print(list_types)
print(possible_types)

[[], ['uncertain'], ['advertisement call'], ['territorial call'], ['flight call'], ['advertisement call', ' chorus'], ['reproductive call ?'], ['alarm call'], ['call'], ['mating call'], ['social call'], ['advertisement call', ' territorial call'], ['song'], ['call', ' mechanical sound'], ['mechanical sound'], ['sniffing'], ['call', ' song'], ['call', ' scolding'], ['canto'], ['call', ' subsong'], ['alarm call', ' llamadas de contacto'], ['voz de contacto de adulto.'], ['song', ' llamado de adulto.'], ['voz de contacto de pichón.'], ['duet', ' song'], ['duet'], ['alarm call', ' call'], ['aberrant'], ['dueto'], ['duet', ' song', ' song in duet'], ['song', ' duo'], ['fast low call'], ['chamado'], ['dawn song'], ['call', ' duet'], ['call', ' wing sound'], ['alarm call', ' call', ' juvenile call'], ['song', ' long song'], ['song', ' complex song'], ['song', " 'laughing' song"], ['song', " 'barking' song"], ['song', ' simple song'], ['call', ' dawn song', ' duet'], ['call', ' duet', ' song'], ['song', ' territorial song'], ['call', ' cackling calls'], ['subsong'], ['call?'], ['song', ' laughing song'], ['call', ' song', ' song/call'], ['song', ' 5-noted song'], ['song', ' agitated song'], ['song', ' 4-noted song'], ['duet', ' dawn duet'], ['call', ' cackling call', ' female?'], ['alarm call', ' alarm call of an adult'], ['song?'], ['song', ' "'], ['song', ' "laughing" song'], ['song', ' myadestes occidentalis'], ['call', ' calls'], ['begging call'], ['begging call', ' call'], ['chase call'], ['call', ' day song'], ['subsong', ' chase call'], ['drumming', ' song'], ['begging call', ' drumming'], ['duet', ' song', ' duet song'], ['call', ' whistle call'], ['duet', ' flight call', ' song', ' duet.'], ['contact call'], ['call', ' various different calls and whistles'], ['song', ' subsong'], ['call', ' calls', ' females'], ['call', ' contact call'], ['call', ' song', ' two different calls'], ['song', ' dueto'], ['alarm call', ' song'], ['song', ' short and long songs'], ['begging call', ' song'], ['vocalizations by a young bird learning to sing'], ['duet', ' song', ' subsong'], ['song', ' immature song'], ['flight call', ' song'], ['alarm call', ' flight call'], ['call', ' flight call'], ['canto de voo'], ['call', ' take-off calls'], ['call', ' (flight?) calls'], ['call', ' llamado de cría'], ['nocturnal flight call'], ['flight call', ' flight calls'], ['call', ' song', ' call and song in flight'], ['call', ' Musical calls'], ['call', ' contact calls'], ['song', ' estridulación'], ['call', ' flight call', ' song'], ['flight song'], ['call', ' calls on takling flight'], ['flight call', ' frogs'], ['call', ' song', ' contact call'], ['call', ' contacts call'], ['song', " 'cascade' and song", ' pb'], ['call', ' song', ' natural song', " then 'cascade' and call after pb"], ['call', ' chatters calls'], ['chatter from flock after playback (like natural)'], ['call', ' song', ' excitement chatter'], ['chatter'], ['alarm call', ' anfibios'], ['aberrant', ' call', ' duet', ' song', ' Complex song'], ['alarm call', ' call', ' song'], ['alarm call', ' call', ' duet', ' subsong'], ['call', ' duet', ' song', ' duet song. calls'], ['call', ' song', ' subsong'], ['call', ' excited call'], ['call', ' agitated calls'], ['alarm call', ' alarm calls'], ['call', ' duet', ' calls'], ['call', ' duet', ' flight call', ' wing-flapping'], ['canto em voo'], ['call', ' calls', ' perched'], ['call', ' displaying'], ['alarm call', ' subsong'], ['call', ' calls', ' interaction calls'], ['song', ' domestic dogs'], ['call', ' flight call', ' very agitated calls of juvenile'], ['call', ' calls in flight.'], ['song', ' song in flight'], ['song', ' agitated song in flight'], ['wing sound'], ['call', ' song', ' song. calls.'], ['call', ' interaction calls'], ['call', ' duet', ' duets'], ['call', ' 2 call types'], ['aberrant call'], ['dawn song', ' song'], ['song', ' morning song'], ['call', ' squabble in flight'], ['call', ' chase call', ' wing sound'], ['call', ' huit notes'], ['call', ' duet', ' call duet'], ['uncertain', ' carro'], ['alarm call', ' huits and whistles'], ['dawnsong'], ['begging call', ' hatchling or nestling'], ['interaction call'], ['song', ' song a'], ['call', ' song', ' calls', ' bill snaps'], ['song', ' down song'], ['call', ' song', ' songs a and b and calls'], ['call', ' duet', ' aggressive call', ' bill snap'], ['alarm call', ' duet'], ['call', ' daytime call'], ['canto/briga'], ['call', ' different calls'], ['call', ' daytime calls'], ['call', ' daytime call', ' interaction vocalization'], ['song', ' duet?'], ['call', ' song', ' song a'], ['call', ' two call types'], ['call', ' interaction call'], ['canto/chamado'], ['call', ' dawn calls'], ['call', ' duet', ' song', ' song b in duet and calls'], ['call', ' short descending tremolo call'], ['social'], ['begging call', ' call', ' song'], ['song', ' songs'], ['call', ' song', ' quiet-singing while holding nesting material'], ['call', ' calls', ' excited calls'], ['call', ' calls from perch and in flight'], ['song', ' fligth song'], ['call', ' song', ' song and calls in flight'], ['song', ' wing whirrs'], ['call', ' bill click. call (weak).'], ['', ' clicks'], ['alarm call', ' hatchling or nestling'], ['call', ' ', ' soft call by nest box'], ['call', ' flight call', ' nocturnal flight call', ' night flight call'], ['clicking'], ['alarm call', ' nocturnal flight call'], ['begging call', ' call', ' flight call'], ['alarm call', ' call', ' duet', ' nocturnal flight call', ' urban sounds'], ['call', ' clicking'], ['aberrant', ' duet'], ['', ' cleaking', ' scream'], ['call', ' traffic on freeway'], ['begging call', ' ', ' cleaking'], ['flight call', ' nocturnal flight call'], ['não sei'], ['call', ' nocturnal flight call'], ['call', ' hatchling or nestling'], ['bill snapping'], ['song', ' song. rolls.'], ['alarm call', ' call', ' wing sound'], ['call', ' song', ' calls'], ['call', ' duet', ' song', ' calls', ' song in duet'], ['call', ' duet', ' song', ' song in duet', ' calls'], ['myiopsitta monachus'], ['song', ' não'], ['call', ' calls', ' perched and in flight'], ['duet', ' flight call'], ['flight call', ' chorus'], ['camptostoma obsoletum', ' myiopsitta monachus', ' setophaga pitiayumi', ' sicalis flaveol'], ['automoviles', ' golpes', ' gorriones'], ['couple in copulation'], ['call', ' dawn call'], ['call', ' urban sounds'], ['call', ' calls at roost'], ['song', ' song b'], ['aberrant', ' alarm call'], ['call', ' calls from pair at nest hole'], ['hiss'], ['call', ' flight call', ' calls'], ['call', ' Territorial call'], ['alarm call', ' call', ' flight call'], ['alarm call', ' camera zoom/shutter'], ['duet', ' wing sound', ' aggressive call'], ['chorus'], ['calling in flight'], ['duet', ' song', ' Polioptila dumicola', ' Aramydes ypecaha'], ['call', ' howler monkeys'], ['dawn chorus'], ['songs 3 groups'], ['duet', ' chorus'], ['call', ' chorus'], ['song', " dawn 'songs'"], ['imitation', ' song', ' mimicry/imitation'], ['song', ' imitações.'], ['call', ' immature calls'], ['mimic'], ['call', ' song', ' calls. song.'], ['call', ' song', ' group call'], ['call', ' nestling calls and adult alert'], ['alarm call', ' call', ' attack calls', ' collective calls', ' sex uncer'], ['call', ' dawn song'], ['call', ' dawn song', ' song'], ['territorial song? early morning'], ['call', ' flight call', ' subsong'], ['song', ' half song'], ['call', ' song', ' (alarm) calls. song.'], ['song', ' one-noted song'], ['call', ' dawn song', ' song', ' subsong'], ['call', ' dawn'], ['call', ' call of a juvenile'], ['song', ' dawn'], ['vocalization of the couple'], ['call', ' response to playback'], ['aberrant', ' song'], ['song', " 'purweer' song"], ['song', ' full song'], ['song', ' rhinella marina'], ['Warning call en respuesta a la imitación que yo hago con mi propio silibido'], ['Stress an excited call'], ['no idea'], ['call', ' (alarm) calls'], ['call', ' calls of adult male'], ['call', ' call of female-plumaged bird'], ['call', ' call of adult female'], ['begging call', ' begging calls of juvenile'], ['call', ' imitation', ' song'], ['imitation', ' song'], ['call', ' imitation', ' song', ' subsong'], ['call', ' song', ' call or song'], ['song', ' pb'], ['call', ' imitation', ' mimicry/imitation'], ['nocturnal flight call', ' song'], ['call', ' single call'], ['call', ' song', ' aggressive call'], ['call', ' calls of a pair'], ['alarm calls?'], ['song', ' a single song'], ['call', ' song', ' song or call'], ['alarm call', ' song', ' alarm calls. song.'], ['song', ' short songs'], ['call', ' dry gravelly calls.'], ['alarm call', ' alarm calls.'], ['song', ' short'], ['song', ' long'], ['call', ' dry gravelly calls. short calls'], ['call', ' song phrase'], ['alarm call', ' call', ' alarm calls. dry gravelly calls.'], ['alarm call', ' flight call', ' song'], ['call', ' drumming', ' song'], ['song', ' nyctibeus griseus'], ['call', ' wingbeats'], ['call', ' song', ' interaction calls'], ['call', ' Hoot'], ['call', ' bater de asas'], ['call', ' batido de asas'], ['song', ' wing sound', ' display call'], ['song', ' wing sound'], ['duet', ' interspecific duet'], ['call', ' song', ' possibly calls'], ['call', ' calls', ' two birds'], ['chamado/canto'], ['song', ' daytime song'], ['call', ' calls (variation)'], ['song', ' aggressive call'], ['song', ' moorning song'], ['song', ' variation song'], ['call', ' (probably alarm) calls'], ['?'], ['whistles'], ['call', ' whistle. (probably alarm) calls'], ['call', ' reclamo'], ['call', ' alarm? call'], ['call', ' trrt calls in flight'], ['call', ' duet', ' nocturnal flight call'], ['song', ' canto crepuscular'], ['dawn song', ' chase call'], ['alarm call', ' call', ' duet'], ['call', ' chase calls'], ['call', ' vaca (cow)'], ['call', ' song', ' mosquitos'], ['duet', ' song', ' song and duet'], ['song', ' alternate song'], ['duet?'], ['call', ' excited calls'], ['call', ' alternate call'], ['call', ' song', ' alternate song', ' calls'], ['song', ' song (variant)'], ['song', ' gutural sound'], ['call', ' whinny chorus'], ['call', ' song', ' song in chorus'], ['alarm call', ' call', ' flight call', ' song', ' subsong'], ['alarm call', ' call', ' flight call', ' son'], ['flight call', ' song', ' flight calls', ' then song'], ['call', ' song', ' chorus'], ['call', ' grunt'], ['call', ' communal murmuring', ' contact calls'], ['call', ' communal murmuring of flock'], ['song', ' chorus'], ['call', ' A sound that went on for minutes', ' a low machine like sound between the crackles'], ['call', ' gurgling call'], ['call', ' Short song?'], ['furnarius rufus', ' pitangus sulphuratus'], ['call', ' duet', ' subsong'], ['song', ' annoying cricket'], ['aberrant', ' alarm call', ' Distress call in hand'], ['call', ' song', ' song with several variations. all sounds made by wtst.'], ['song', ' chouic', ' una especie de chouic'], ['calls'], ['alert for a monkey group (sapajus nigritus)'], ['song', ' batido de asas (estalo)'], ['call', ' song', ' perched calls'], ['call', ' cooing trill'], ['song', ' ship engine in the canal'], ['subsong', ' bill snaps'], ['song', ' voces humanas y música.'], ['call', ' voces humanas', ' música'], ['call', ' morning call?'], ['call', ' song', ' (alarm) calls. one short song'], ['call', ' song', ' half song'], ['song', ' long duetting song'], ['alarm call', ' flight call', ' donkey vocalizing.'], ['flight call', ' taking off'], ['flight call', ' Take-off calls'], ['call', ' take-off call'], ['call', ' flush call'], ['call', ' flight call', ' nocturnal flight call', ' song'], ['alarm call', ' flight and alarm calls'], ['call', ' pew series'], ['song', ' song (variation)'], ['call', ' song', ' chase call'], ['song', ' short song'], ['dawn song', ' duet'], ['call', ' calls of chicks'], ['aberrant', " haven't heard this before in this sp", ' possibly f'], ['call', ' duet', ' duet call'], ['call', ' territorial calls'], ['call', ' "tawny-like"'], ['aberrant', ' begging call', ' call', ' song', ' subsong'], ['alarm call', ' begging call', ' call', ' flight call'], ['flight call', ' rising call'], ['call', ' mating calls'], ['call', ' flock'], ['alarm call', ' anxiety calls'], ['alarm call', ' call', ' anxiety call'], ['begging call', ' call', ' flight call', ' song', ' subsong'], ['call', ' flock; dormitory'], ['call', ' sounds of interaction'], ['chasing call'], ['call', ' chasing call'], ['call', ' chase call'], ['call', ' subsong', ' "subsong"', ' calls'], ['call', ' calls', " 'croaking' calls"], ['call', ' Wail call'], ['call', ' Kew call'], ['drumming'], ['tamborileo'], ['drumm'], ['call', ' pair'], ['call', ' agitated call'], ['drum'], ['call', ' drumming'], ['call', ' calls pair'], ['mechanical'], ['call', ' taps and calls'], ['call', ' "chick-burrrr" call.'], ['alarm churrr'], ['call', ' short call'], ['song', ' uncertain'], ['call', ' double-noted call'], ['call', ' double- and single-noted calls'], ['alarm call', ' duet', ' song'], ['call', ' duet', ' song', ' contact call'], ['call', ' wingnoise'], ['call', ' mew calls'], ['flight call', ' song', ' flight calls', ' songs'], ['begging call', ' subsong'], ['song', ' Batido de asas'], ['song', ' bater de asas'], ['call', ' three different calls'], ['song', ' rattle'], ['uncertain', ' ratle'], ['rattle'], ['call', ' rattle'], ['rattles'], ['dawn song', ' song', ' subsong', ' dusk song'], ['dusk calls'], ['call', ' song', ' dusk song'], ['call', ' long rattling call'], ['call', ' call (long rattle)'], ['song', ' possibly in response to playback'], ['song phrases'], ['call', ' calls in flight'], ['group'], ['duet', ' flight call', ' song'], ['call', ' calls', ' take-off calls'], ['flight chorus'], ['call', ' tew'], ['display flight'], ['song', ' variant of normal song'], ['call', ' chatter'], ['song', ' fast and normal song'], ['call', " puttering trill and 'chiff' call"], ['begging call', ' duet', ' song'], ['call', ' song', ' hatchling or nestling'], ['song', ' single song'], ['aberrant', ' dawn song', ' subsong'], ['song', ' variant song'], ['rattling'], ['feeding call'], ['song', ' song and growls'], ['growl'], ['song', ' growl'], ['call', ' calls by presumed pair'], ['song', " ('slow') alternate song"], ['call', ' song', " ('slow') alternate song", ' interaction calls'], ['song', " ('fast') alternate song"], ['call', ' song', ' two song types'], ['song', ' (slow) alternate song'], ['song', ' (fast) alternate song'], ['song', ' excited song'], ['call', ' song', ' quiet calls'], ['chamado de contato'], ['call', ' Batido de asas'], ['call', ' song', ' calls c and d and song'], ['call', ' song', ' various different calls and song'], ['call', ' two different calls'], ['imitation', ' imitando a Accipiter bicolor'], ['song', ' "micrastur semitorquatus like" song'], ['call', ' calls of 5 birds'], ['call', ' calls of 8 birds'], ['call', ' falcon imitation?'], ['falcon imitation?'], ['display call'], ['alarm call', ' call', ' duet', ' song'], ['call', ' duet', ' song', ' duet song'], ['call', ' calls', ' pair'], ['duet', ' song', ' chorus'], ['song', ' howler monkeys'], ['call', ' contact call?'], ['alarm?'], ['call', ' excited calls of 2 birds after playback'], ['call', ' series of single-note calls'], ['call', ' excited call after playback'], ['call', ' song', ' complex song and call'], ['call', ' unusual calls'], ['song', ' ', ' simple song'], ['call', ' calls on perch', ' then in flight'], ['call', ' calls pearched'], ['call', ' song', ' calls', ' songs'], ['song', ' immature'], ['aberrant', ' alarm call', ' call', ' alternate call'], ['song', ' song at dawn'], ['call', ' distress call'], ['call', ' communal calls'], ['song', ' wing-beats'], ['call', ' calls of c 10 birds while foraging on forest floor'], ['call', ' Social contact call'], ['song', ' song or calls?'], ['call', ' dawn song', ' duet', ' song'], ['call', ' excited calls in flight'], ['song', ' wind'], ['begging call', ' begging calls of 2 fledged juveniles'], ['song', ' nupcial song'], ['song', ' song?'], ['song', ' nuptial song'], ['fligth song'], ['call', ' song', ' song from perch', ' then take-off call'], ['aberrant', ' call'], ['call', ' aggressive call'], ['call', ' rolling call'], ['chamado estranho'], ['uncertain', ' different song'], ['call', ' dawn song', ' dusksong'], ['call', ' series call'], ['dawn song', ' subsong'], ['Distress call'], ['batido de asas'], ['song', ' ninguno'], ['call', ' song', ' wing whirr'], ['call', ' subsong', ' wing sound'], ['call', ' song', ' song and half song'], ['call', ' song', ' wing sounds'], ['call', ' wing noise'], ['song', ' trill song'], ['duet', ' subsong'], ['dawn song', ' duet', ' song'], ['call', ' flight chase call'], ['song', ' growl', ' mechanical sounds'], ['song', ' gargling'], ['call', ' song', ' song with introductory calls.'], ['song', ' grunts'], ['call', ' calls by flushed flock'], ['chatter after playback'], ['call', ' calls by same group'], ['alarm call', ' alarm call of 4 birds'], ['call', ' song', ' excited call'], ['call', ' song', ' call/song'], ['alarm call', ' call', ' song', ' calls'], ['call', ' song', ' Batido de asas'], ['call', ' song', ' calls', ' agitated song', ' wing noise'], ['call', ' song', ' excited calls'], ['lamento'], ['moan cascade'], ['moan'], ['wing flaps'], ['alarm call', ' alarm calls when flushed'], ['call', ' song', ' night song'], ['single hoot'], ['chamdo'], ['call', ' llamado-call'], ['aberrant', ' song', ' Canto distorcido.'], ['call', ' call (snarl)'], ['call', ' subsong', ' calls'], ['call', ' call from perch'], ['call', ' call/ song?'], ['song', ' wing flaps'], ['wing beats mechanical sound'], ['song', ' wing sounds'], ['growls'], ['flight call', ' flight calls of pair'], ['call', ' calls by perched pair and begging young'], ['flight call', ' flight calls of flock'], ['flight call', ' different flight calls'], ['call', ' calls on perch'], ['call', ' calls while feeding'], ['lekking'], ['call', ' bill snapping'], ['call', ' agonistic calls'], ['call', ' long call'], ['call', ' song', ' (song-like) call'], ['song', ' canto al amanecer'], ['call', ' chip call'], ['call', ' Keek series and a harsh grating attack call not recognized by Merlin app'], ['call', ' Tews', ' Psits', ' Keek series', ' a harsh noisy call with pitch range 1-12 kHz lasting'], ['call', ' flight call', ' song', ' scream series', ' keek'], ['call', ' flight call', ' scream series'], ['song', ' song while perched'], ['flight call', ' subsong'], ['call', ' calls (alarm?)'], ['flight call', ' song', ' song in flight'], ['flight call', ' song', ' song from perch'], ['call', ' song?'], ['call', ' song', ' calls. song'], ['call', ' contact call female'], ['call', ' flight call', ' calls', ' flight calls'], ['alarm call', ' contact and alarm calls'], ['call', ' morning chorus'], ['song', ' short version'], ['song', ' complete song maybe missing the first note.'], ['call', ' (alarm?) calls'], ['call', ' song', ' calls or song'], ['call', ' trilled call'], ['song', ' dusk song'], ['call', ' various different calls'], ['vocalização em perseguição intraespecífica'], ['song', ' display wing-flutter'], ['song', ' song 2'], ['song', ' single-noted song'], ['call', ' song', ' calls', " daytime 'song'"], ['song', ' dusk'], ['call', ' chatter call'], ['call', ' rattle song'], ['song', ' other song'], ['begging call', ' dawn song', ' song'], ['song', ' song after playback'], ['song', ' end of alarm'], ['call', ' song', ' calls song'], ['call', ' song', ' normal and atypical songs'], ['alarm call', ' song', ' beak sounds'], ['song', ' bill snapping'], ['song', ' bill snapings'], ['song', ' bill snap'], ['song', ' snaps'], ['song', ' clicking through the beak'], ['song', ' bater de bico'], ['call', ' bater de bico'], ['song', ' also doing cracks (estalos in port.)'], ['call', ' copulation-calls'], ['call', ' in nest'], ['scold from ground and in flight'], ['alarm call', ' call', ' possibly an alarm call'], ['scold from ground'], ['call', ' calls from ground and in flight'], ['call', ' calls 2 birds on gr

In [8]:
print(
    f"Percentage of train audio with type: {(df_train['type'] != '[]').sum() / len(df_train) * 100:.2f}%"
)

Percentage of train audio with type: 63.50%

For now I will just use a `LabelEncoder` from Scikit-learn to encode the primary label. I fit the encoder on `df_taxonomy` since there are some animals that are only in either `train_audio` or `train_soundscapes`.

In [9]:
from sklearn.preprocessing import MultiLabelBinarizer

le_classes = MultiLabelBinarizer()
le_primary = MultiLabelBinarizer()

le_classes.fit(df_taxonomy["class_name"].apply(lambda x: [x]))
le_primary.fit(df_taxonomy["primary_label"].apply(lambda x: [x]))

print(f"Number of Classes: {len(le_classes.classes_)}")
print(f"Number of Species: {len(le_primary.classes_)}")

Number of Classes: 5
Number of Species: 234

In [10]:
df_taxonomy

,primary_label,inat_taxon_id,scientific_name,common_name,class_name
0,1161364,1161364,Guyalna cuta,Guyalna cuta,Insecta
1,116570,116570,Caiman yacare,Southern Spectacled Caiman,Reptilia
2,1176823,1176823,Leptodactylus luctator,Wrestler Frog,Amphibia
3,1491113,1491113,Adenomera guarani,Guaraní leaf-litter frog,Amphibia
4,1595929,1595929,Lysapsus limellum,Uruguay Harlequin Frog,Amphibia
...,...,...,...,...,...
229,yebela1,16714,Elaenia flavogaster,Yellow-bellied Elaenia,Aves
230,yecmac,73272,Primolius auricollis,Golden-collared Macaw,Aves
231,yecpar,19215,Brotogeris chiriri,Yellow-chevroned Parakeet,Aves
232,yehcar1,1432779,Daptrius chimachima,Yellow-headed Caracara,Aves
233,yeofly1,16567,Tolmomyias sulphurescens,Yellow-olive Flatbill,Aves

Since we only have primary labels and not class names in `df_train_soundscapes` we have a mapping from primary label to class name.

In [11]:
primary_to_class = {}
for primary_label, class_name in zip(
    df_taxonomy["primary_label"], df_taxonomy["class_name"]
):
    primary_to_class[primary_label] = class_name

In [12]:
from datetime import datetime


def time_to_seconds(t):
    dt = datetime.strptime(t, "%H:%M:%S")
    return 3600 * dt.hour + 60 * dt.minute + dt.second


x_train_files = df_train[["filename"]]
x_train_soundscapes_files = df_train_soundscapes[["filename", "start", "end"]]
x_train_soundscapes_files["start"] = x_train_soundscapes_files["start"].apply(
    time_to_seconds
)
x_train_soundscapes_files["end"] = x_train_soundscapes_files["end"].apply(
    time_to_seconds
)
x_train_soundscapes_files

                                       filename  start  end
0     BC2026_Train_0039_S22_20211231_201500.ogg      0    5
1     BC2026_Train_0039_S22_20211231_201500.ogg      5   10
2     BC2026_Train_0039_S22_20211231_201500.ogg     10   15
3     BC2026_Train_0039_S22_20211231_201500.ogg     15   20
4     BC2026_Train_0039_S22_20211231_201500.ogg     20   25
...                                         ...    ...  ...
1473  BC2026_Train_0055_S22_20220219_200000.ogg     35   40
1474  BC2026_Train_0055_S22_20220219_200000.ogg     40   45
1475  BC2026_Train_0055_S22_20220219_200000.ogg     45   50
1476  BC2026_Train_0055_S22_20220219_200000.ogg     50   55
1477  BC2026_Train_0055_S22_20220219_200000.ogg     55   60

[1478 rows x 3 columns]

In [13]:
y_train_classes = le_classes.transform(df_train["class_name"].apply(lambda x: [x]))
print(y_train_classes.shape)

y_train_primary = le_primary.transform(df_train["primary_label"].apply(lambda x: [x]))
print(y_train_primary.shape)

(35549, 5)
(35549, 234)

In [14]:
y_soundscapes_classes = le_classes.transform(
    df_train_soundscapes["primary_label"]
    .apply(lambda x: x.split(";"))
    .apply(lambda x: list({primary_to_class[primary_label] for primary_label in x}))
)
print(y_soundscapes_classes.shape)

y_soundscapes_primary = le_primary.transform(
    df_train_soundscapes["primary_label"].apply(lambda x: x.split(";"))
)
print(y_soundscapes_primary.shape)

(1478, 5)
(1478, 234)

Our functions for analyzing the sounds should probably take as input a row from either `x_train` or `x_train_soundscapes`.

In [15]:
x_train_soundscapes_files.iloc[:10]

                                    filename  start  end
0  BC2026_Train_0039_S22_20211231_201500.ogg      0    5
1  BC2026_Train_0039_S22_20211231_201500.ogg      5   10
2  BC2026_Train_0039_S22_20211231_201500.ogg     10   15
3  BC2026_Train_0039_S22_20211231_201500.ogg     15   20
4  BC2026_Train_0039_S22_20211231_201500.ogg     20   25
5  BC2026_Train_0039_S22_20211231_201500.ogg     25   30
6  BC2026_Train_0039_S22_20211231_201500.ogg     30   35
7  BC2026_Train_0039_S22_20211231_201500.ogg     35   40
8  BC2026_Train_0039_S22_20211231_201500.ogg     40   45
9  BC2026_Train_0039_S22_20211231_201500.ogg     45   50

The example function below is how I think it can be good to write functions for finding features from the data.

In [16]:
# example function for getting features
def example_analysis(x):
    if x.shape == (1,):  # Audio
        audio, sr = librosa.load(
            f"../birdclef-2026/train_audio/{x['filename']}", sr=32000
        )
    elif x.shape == (3,):  # Soundscape
        audio, sr = librosa.load(
            f"../birdclef-2026/train_soundscapes/{x['filename']}",
            sr=32000,
            offset=x["start"],
            duration=x["end"] - x["start"],
        )
    else:
        raise ValueError

    # plt.title(f"{x['filename']}")
    S = np.abs(librosa.stft(audio))
    S_db = librosa.amplitude_to_db(S)
    # librosa.display.specshow(S_db)
    # plt.show()

    return pd.Series({"spec_min": S_db.min(), "spec_max": S_db.max()})

Takes about ~20 mins to load the whole dataset (can probably be improved)

In [ ]:
from tqdm import tqdm
import warnings

warnings.filterwarnings("ignore", module="librosa")

features = pd.DataFrame(
    [
        example_analysis(row)
        for _, row in tqdm(x_train_files.iterrows(), total=len(x_train_files))
    ]
)